name: Bump version and create a release

on:
  push:
    branches:
      - master

jobs:
  create:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bump2version

      - name: Bump version and push tag
        id: tag_version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          bump2version patch --allow-dirty
          echo ::set-output name=RELEASE_VERSION::$(cat .bumpversion.cfg | grep current_version | sed 's/^.* = //')

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.RELEASE_VERSION }}
          release_name: Release ${{ steps.tag_version.outputs.RELEASE_VERSION }}
          draft: false
          prerelease: false
